apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: stage-nginx-namespace
spec:
  type: ClusterIP
  ports:
    - port: 200
      protocol: TCP
      targetPort: 200
      name: http
  selector:
    app.kubernetes.io/name: external-app
    app.kubernetes.io/instance: nginx
